name: CI

on:
  push:
    branches: "*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Setup Nix envirionment
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-24.05
      - uses: cachix/cachix-action@v14
        with:
          name: lambda-kansai-github
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: nicknovitski/nix-develop@v1
      - run: nix develop --extra-experimental-features "nix-command flakes"

      # Run CI jobs
      - name: Install
        run: |
          spago install
          pnpm install --frozen-lock

      - name: Build
        run: |
          pnpm run build
          pnpm -F "./example" run build

      - name: Test
        run: pnpm run test

      - name: Check
        run: |
          pnpm run check
          pnpm -F './example' run check
